/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.form;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import silab.sd.personapp.view.component.validator.impl.RequiredStringValidator;

/**
 *
 * @author lukaj
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public FrmMain() {
        initComponents();
        prepareComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPersonForm1 = new silab.sd.personapp.view.form.AddPersonForm();
        menuMain = new javax.swing.JMenuBar();
        menuConfiguration = new javax.swing.JMenu();
        miPersonConfiguration = new javax.swing.JMenuItem();
        menuPerson = new javax.swing.JMenu();
        menuItemAddPerson = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuConfiguration.setText("Configuration");

        miPersonConfiguration.setText("Person");
        miPersonConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPersonConfigurationActionPerformed(evt);
            }
        });
        menuConfiguration.add(miPersonConfiguration);

        menuMain.add(menuConfiguration);

        menuPerson.setText("Person");

        menuItemAddPerson.setText("Add");
        menuItemAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddPersonActionPerformed(evt);
            }
        });
        menuPerson.add(menuItemAddPerson);

        menuMain.add(menuPerson);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPersonForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPersonForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddPersonActionPerformed
        //addPersonForm1.setVisible(true);
        JDialog dialog = new FrmAddPersonDependsOnConfiguration(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemAddPersonActionPerformed

    private void miPersonConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPersonConfigurationActionPerformed
        JDialog dialog = new FrmPersonConfiguration(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_miPersonConfigurationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private silab.sd.personapp.view.form.AddPersonForm addPersonForm1;
    private javax.swing.JMenu menuConfiguration;
    private javax.swing.JMenuItem menuItemAddPerson;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuPerson;
    private javax.swing.JMenuItem miPersonConfiguration;
    // End of variables declaration//GEN-END:variables

    private void prepareComponents() {
        addPersonForm1.getInputFirstname().setValidator(new RequiredStringValidator());
        addPersonForm1.getInputFirstname().getLblText().setText("Firstname:");
        addPersonForm1.getInputFirstname().getLblErrorValue().setText("");

        addPersonForm1.getInputLastname().setValidator(new RequiredStringValidator());
        addPersonForm1.getInputLastname().getLblText().setText("Lastname:");
        addPersonForm1.getInputLastname().getLblErrorValue().setText("");

        addPersonForm1.getInputGender().getLblText().setText("Gender");
        addPersonForm1.getInputGender().getLblErrorValue().setText("");

        addPersonForm1.getInputGender().getCbValue().removeAllItems();
        /*inputGender.getCbValue().addItem("Male");
        inputGender.getCbValue().addItem("Female");*/

        List<String> genders = new ArrayList<String>() {
            {
                add("Male");
                add("Female");
            }
        };
        addPersonForm1.getInputGender().getCbValue().setModel(new DefaultComboBoxModel<>(genders.toArray()));

        addPersonForm1.getInputBirthday().getLblText().setText("Birthday:");
        addPersonForm1.getInputBirthday().getLblErrorValue().setText("");
        
        addPersonForm1.setVisible(false);

    }
}
