/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.form;

import javax.swing.JOptionPane;
import silab.sd.personapp.utils.PersonConfiguration;
import silab.sd.personapp.utils.Utils;

/**
 *
 * @author lukaj
 */
public class FrmPersonConfiguration extends javax.swing.JDialog {

    /**
     * Creates new form FrmPersonConfiguration
     */
    public FrmPersonConfiguration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputComboName = new silab.sd.personapp.view.component.InputComboPanel();
        inputComboLastname = new silab.sd.personapp.view.component.InputComboPanel();
        inputComboGender = new silab.sd.personapp.view.component.InputComboPanel();
        inputComboBirthday = new silab.sd.personapp.view.component.InputComboPanel();
        inputComboMarried = new silab.sd.personapp.view.component.InputComboPanel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputComboLastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputComboBirthday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputComboName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputComboMarried, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputComboName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputComboLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputComboBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputComboMarried, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int firstname = inputComboName.getCbValue().getSelectedIndex();
        int lastname = inputComboLastname.getCbValue().getSelectedIndex();
        int gender = inputComboGender.getCbValue().getSelectedIndex();
        int birthday = inputComboBirthday.getCbValue().getSelectedIndex();
        int married = inputComboMarried.getCbValue().getSelectedIndex();
        Utils.setPersonConfiguration(new PersonConfiguration(firstname, lastname, gender, birthday, married));
        JOptionPane.showMessageDialog(this, "You have successfully saved new person configuration!", "Saved", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private silab.sd.personapp.view.component.InputComboPanel inputComboBirthday;
    private silab.sd.personapp.view.component.InputComboPanel inputComboGender;
    private silab.sd.personapp.view.component.InputComboPanel inputComboLastname;
    private silab.sd.personapp.view.component.InputComboPanel inputComboMarried;
    private silab.sd.personapp.view.component.InputComboPanel inputComboName;
    // End of variables declaration//GEN-END:variables

    private void prepareComponents() {
        inputComboName.getLblText().setText("Firstname:");
        inputComboName.getLblErrorValue().setText("");
        inputComboName.getCbValue().removeAllItems();
        inputComboName.getCbValue().addItem("InputTextfieldPanel");
        
        inputComboLastname.getLblText().setText("Lastname:");
        inputComboLastname.getLblErrorValue().setText("");
        inputComboLastname.getCbValue().removeAllItems();
        inputComboLastname.getCbValue().addItem("InputTextfieldPanel");
        
        inputComboGender.getLblText().setText("Gender:");
        inputComboGender.getLblErrorValue().setText("");
        inputComboGender.getCbValue().removeAllItems();
        inputComboGender.getCbValue().addItem("InputTextfieldPanel");
        inputComboGender.getCbValue().addItem("InputComboPanel");

        inputComboBirthday.getLblText().setText("Birthday:");
        inputComboBirthday.getLblErrorValue().setText("");
        inputComboBirthday.getCbValue().removeAllItems();
        inputComboBirthday.getCbValue().addItem("InputTextfieldPanel");
        inputComboBirthday.getCbValue().addItem("InputDateSeparateElements");

        inputComboMarried.getLblText().setText("Married:");
        inputComboMarried.getLblErrorValue().setText("");
        inputComboMarried.getCbValue().removeAllItems();
        inputComboMarried.getCbValue().addItem("InputTextfieldPanel");
        inputComboMarried.getCbValue().addItem("InputComboPanel");
    }
}
