/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.component;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import silab.sd.personapp.view.component.validator.Validator;

/**
 *
 * @author lukaj
 */
public class InputComboPanel extends javax.swing.JPanel implements GetValue {

    private Validator validator;

    /**
     * Creates new form InputComboPanel
     */
    public InputComboPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        cbValue = new javax.swing.JComboBox<>();
        lblErrorValue = new javax.swing.JLabel();

        lblText.setText("jLabel1");

        cbValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValueActionPerformed(evt);
            }
        });

        lblErrorValue.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorValue.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorValue, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(cbValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbValueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cbValue;
    private javax.swing.JLabel lblErrorValue;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables

    public JComboBox<Object> getCbValue() {
        return cbValue;
    }

    public void setCbValue(JComboBox<Object> cbValue) {
        this.cbValue = cbValue;
    }

    public JLabel getLblErrorValue() {
        return lblErrorValue;
    }

    public void setLblErrorValue(JLabel lblErrorValue) {
        this.lblErrorValue = lblErrorValue;
    }

    public JLabel getLblText() {
        return lblText;
    }

    public void setLblText(JLabel lblText) {
        this.lblText = lblText;
    }

    @Override
    public Object getValue() throws Exception {
        return cbValue.getSelectedItem();
    }

    public void setValidator(Validator validator) {
        this.validator = validator;
    }

}
